### ISSUE TITLE
Approval Flow Configuration

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/OnBot#1]
I 'm trying to setup onBot with Slack integration.
I not clear about the three configurations from the wiki page
https://onedevops.atlassian.net/wiki/spaces/OO/pages/99680636/Approval+Flow+Configuration
1) Request URL
2) Options Load URL
3) Redirect URL 

How do I configure these URLs? Can you share any sample configurations?

**Comment by silverlane** [comment]
Sorry for the delayed response. "Request URL” is the Approval App URL which has been created from the code https://github.com/CognizantOneDevOps/OnBot/tree/master/frameworkservices/workflow . In this case, other 2 URLs are optional. Ensure "Request URL" is accessible from the slack.

**Comment by JeyanthiBalakrishnan** [comment]
Sorry for the delayed response. "Request URL” is the Approval App URL which has been created from the code https://github.com/CognizantOneDevOps/OnBot/tree/master/frameworkservices/workflow . In this case, other 2 URLs are optional. Ensure "Request URL" is accessible from the slack.
